server.port=8888
spring.application.name=eatzy-config-server

# Kích hoạt chế độ đọc từ file cục bộ (thay vì GitHub)
spring.profiles.active=native

# Trỏ thư mục chứa các file config (tìm trong thư mục gốc project)
spring.cloud.config.server.native.search-locations=classpath:/configurations/

# Đăng ký với Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
