server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Database (MariaDB)
spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/eatzy_cart_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT
foodDelivery:
  jwt:
    base64-secret: ${JWT_BASE64_SECRET}
    access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:8640000}
    refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:8640000}

# Security
security:
  oauth2:
    resourceserver:
      jwt: {}
